# Generated by Django 4.2.3 on 2023-07-15 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hanashiai_web', '0004_comments_post_alter_comments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hanashiai_web.post'),
        ),
    ]
