# Generated by Django 4.2.3 on 2023-07-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanashiai_web', '0005_alter_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
