# Generated by Django 4.2.3 on 2023-07-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanashiai_web', '0006_comments_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
